### ISSUE TITLE
"Indoor run" from Watch GT fails to parse

### ISSUE THREAD

**Issue by ediblemanager** [aricooperdavis/Huawei-TCX-Converter#1]
[Here's a link](https://drive.google.com/open?id=1Sd6wKYpA0gWIfsED-JcZi-YC-mk15yEU) to the output file from my Watch GT. The Huawei app is installed on my `Mi Mix 2` which is rooted.

The output from the file is: 

```
---- Input File ----
reading: OKAY
filtering: OKAY
processing gps: OKAY
Something went wrong :-(
```

Shoving a debug line in, I get `Error: list index out of range` - does it need another conditional to catch indoor running stats? Sorry, I'm a bit lost in Python having never written any before.

**Comment by ediblemanager** [comment]
Not sure how I managed to close this!

**Comment by aricooperdavis** [comment]
Well spotted! I initially wrote this script just to extract GPS data, but now we've branched out a bit it doesn't make any sense to extract start time just from gps data, and we should instead extract it from the merged chronologically sorted data. I'll sort this out today :)
