### ISSUE TITLE
Project forked to C#

### ISSUE THREAD

**Issue by azzaNZ** [aricooperdavis/Huawei-TCX-Converter#10]
Not an issue per-se, just a courtesy FYI.

Your parser works really well with my Huawei Watch GT, I found it really useful.

I've forked it to a C# project, and tied it in with GMaps to provide validation of route.
The fork is available here https://github.com/azzaNZ/Huawei-Track-Converter

At time of writing I haven't developed the output to tcx/gpx.  I'll do this in the next few days, before evaluating whether I can be bothered tying it directly to Strava etc.

**Comment by aricooperdavis** [comment]
Fantastic, thanks for sending this my way - I'll add it to the README of this project :)
