### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by juanquetta** [aricooperdavis/Huawei-TCX-Converter#12]
GUI for TCX-converter.
Option to automatically upload files to Strava.

App searches for Hitrack files in the same folder and converts them into TCX files.
Removed validate function, couldn't make it an EXE for some reason with that function in the code.
Cadence/2, pretty sure strava is using strides per minute and not stepsperminute.

P.S. Code might be a little sloppy.

[dist.zip](https://github.com/aricooperdavis/Huawei-TCX-Converter/files/3234217/dist.zip)

**Comment by aricooperdavis** [comment]
This is amazing, thank you!

I think that this is different enough to be its own repository, rather than an update to this one? If you do choose to make it it's own repository then I'll link to on the README if you'd like?

**Comment by aricooperdavis** [comment]
The project has since changed significantly enough for this GUI to be outdated. I will close this issue for the moment. If there is demand for a GUI for this project then we can re-open a new enhancement issue.
