### ISSUE TITLE
SWIMMING MODE

### ISSUE THREAD

**Issue by carlosgeraldo01** [aricooperdavis/Huawei-TCX-Converter#16]
Good afternoon I would like you to implement SWIMMING in this conversion!  Thanks for such codes are great.

**Comment by aricooperdavis** [comment]
I have added swimming as a flag option, so that the exercise type is altered in the resultant TCX, however I can't test this as I don't have a HiTrack file from a swimming activity so don't know what kind of data is available or required. Could you please provide me with a HiTrack file to test with?

**Comment by carlosgeraldo01** [comment]
Good morning here is the HiTrack file link: https://drive.google.com/file/d/1-8QwfxBRc0T3COX0nC2fSJ5_EjdM7y-X/view?usp=drivesdk

Thanks for the code work very well!  Excited to play the swim data for the Strava

**Comment by carlosgeraldo01** [comment]
Hello, I did the tests with the new script with codes for swimming and the only data that shows available is the uptime!  It does not show us heart rate, strokes, distance traveled, swolf etc.  Just to report that the only result provided is the uptime in swimming.  And again thanks for the codes

**Comment by carlosgeraldo01** [comment]
I have re-done the tests and the swimming function is not good!  Measuring only time and nothing else

**Comment by dan1967** [comment]
Hello,
thank you very much for TCX Converter (on github). Your work is great :good:

I have one example of swimming data with real value. You can make easy some change in your converter to get correct data.

Here is original HiTrack file
[https://drive.google.com/drive/folders/0B218WnQMXdvwcVFBbGJWcWVwVW8?usp=sharing](https://drive.google.com/drive/folders/0B218WnQMXdvwcVFBbGJWcWVwVW8?usp=sharing)

Here is report about my swimming

**Total value**
pool length 25m
time 00:06:04
kcal 58
number of strokes 93

**1 - breaststroke**
time 00:00:45
swolf 60
number of strokes 15

**2 - breaststroke**
time 00:00:48
swolf 67
number of strokes 19

**3 - backstroke**
time 00:00:57
swolf 74
number of strokes 17

**4 - backstroke**
time 00:02:11 (with pause, play with my new watch :) )
swolf 148
number of strokes 17

**5 - free style**
time 00:00:36 
swolf 48
number of strokes 12

**6 - free style**
time 00:00:33
swolf 46
number of strokes 13

Thank you
D.Z.

**Comment by CTHRU** [comment]
Thanks for the file Dan1967. I had a look at it, but I must admit I can't relate some numbers in the file to the ones in your report.

What I found up till now: 
*** it looks like the tp=s-r records could be the lap times for swimming, but they don't match the lap times you're mentioning. E.g. the first lap should have taken 60 seconds according to the file (1562227693000 - 1562227633000) whereas your provided data reflect 45 seconds,
*** The SWOLF values can be found 1:1 in the tp=swf records.
*** I can't figure out what the tp=p-f and tp=rs records are, although the latter seem some kind of speed or stroke rate (with no clue to what unit)

Looks like I'll need to go and find a swimming pool myself first to get some extra data...

**Comment by dan1967** [comment]
Huawei developers smoke tooooooo much marijua.. :-)
I try understand swimming hitrack file, compare with Hua Health info...

**My opinion, is impossible convert swimming hitrack file to REAL tcx.** 
Hitrack file is data for Hua health table/graph view, match perfect to hitrack file. But... lot of information is missing. They are stored in the database, maybe.

Hitrack for pool swimming...
s-r - looks like one length, but NO
swf - SWOLF
p-f - number of strokes per minute 
r-f - tempo/speed per minute
This data and UNIT is used ONLY for graph view in Hua Health

No information about laps/pool time, swimming style...

In the end of august I try open water swimming...

ps: 
sorry for my english...

ps2 : 
Huawei Watch is nice toy... i love it, yes, really. For running, biking, mountain walking...gps, heart rate
But for swimming I have Garmin Swim watch.
