### ISSUE TITLE
0m Distances

### ISSUE THREAD

**Issue by aricooperdavis** [aricooperdavis/Huawei-TCX-Converter#18]
Hi
After run the command, all the HiTrack file i try is generating **distance with "0 m"**, as below:
---- Input File ----
reading: OKAY
filtering: OKAY
processing gps: OKAY
processing heart-rate/cadence: OKAY
---- Details ----
sport: Running
start: 2019-07-16 12:10:40
duration: 00:00:56
**distance: 0m**

_Originally posted by @tzeseng in https://github.com/aricooperdavis/Huawei-TCX-Converter/issues/9#issuecomment-512646812_

**Comment by aricooperdavis** [comment]
@tzeseng can you please attach the HiTrack file.

**Comment by DaanVanVugt** [comment]
I'm having the same problem on some of my tracks. Can I send you an example privately?

**Comment by aricooperdavis** [comment]
Closing as a new update has been released. Please re-open if the problem persists.
