### ISSUE TITLE
Managed to convert on Android device

### ISSUE THREAD

**Issue by ediblemanager** [aricooperdavis/Huawei-TCX-Converter#2]
Using `termux` on a rooted device (and ensuring that it had the perms to browse storage), I copied the file (required sudo) from the Huawei app folder onto the `/sdcard/` partition and pointed the converter script to it. This gave me a file that seems to accurately reflect what happened.

I reckon a bash wrapper around the copying and `chown`ing of the file would work as an "automated" solution pre native app.

**Comment by aricooperdavis** [comment]
Fantastic, that's good news! I'm learning the ropes of Android app development to try and get an on-device solution, but this is a great intermediate workaround. If you do make a bash wrapper for windows users then please do share it here for others to use!

**Comment by ediblemanager** [comment]
Native app would be excellent. If I can help, I will! Thanks for your
efforts.

The wrapper on question was one to be used on the Android device to
simplify the copying of the file and running of the conversion script.

I'll create a gist on here once done and link it to this ticket.

**Comment by vivere4you** [comment]
Hi, when I make BackUp not all HiTracks are avalible in .tar file. Do you know why? And could you write some know-how about how to root andorid device? Becouse I was searching and I nothing founded.

**Comment by ediblemanager** [comment]
@vivere4you If this is in relation to the Huawei backup app, there might not be too much help here (this is the repo for the conversion script).

As for rooting android devices, that's also way out of scope for this repository. You might want to try https://www.xda-developers.com/ for that.

**Comment by aricooperdavis** [comment]
@vivere4you You need to view the route (the GPS track) in the Huawei Health app before a HiTrack file is generated. I've [mention this explicitly in the instructions](https://github.com/aricooperdavis/Huawei-TCX-Converter/blob/master/README.md#how-to-get-the-hitrack-files). This is because the HiTrack files are not how the tracks are stored, but something used to display them.
