### ISSUE TITLE
Watch GT - no Hitrack files

### ISSUE THREAD

**Issue by PhilLint** [aricooperdavis/Huawei-TCX-Converter#20]
[Watch GT; Huawei P8 Lite ALE-21]
Hey, 
I followed all your steps: opened all runs with maps, made a backup with no password on the SD card and opened it on my computer. However, there are no Hitrackfiles. I tried everything possible, though nothing changed. I appended the backup .apk (somehow is not a .tar) and the unzipped version of it. Maybe, I missed something important. 
Thanks for the help anyways. 
![backup](https://user-images.githubusercontent.com/43146745/62411688-69e9f280-b5f7-11e9-8a0a-87ec2d38ce64.PNG)
![backup_zipped](https://user-images.githubusercontent.com/43146745/62411690-6e161000-b5f7-11e9-8e6f-ecdef33cde44.PNG)

**Comment by CTHRU** [comment]
The apk file is the backup of the Health app itself, somehow you're missing the backup of the data of the app. When you take the backup from your phone, could you verify that you ticked both checkboxes for app and data next to the Health app? It's the latter one that normally generates the tar file. I don't have an SD card slot on my phone, so I selected the option for a shared folder, and this worked.
On a side note, I noticed myself that the backup process is buggy when connecting the phone to a computer and taking the backup via HiSuite on the PC. Even with both boxes ticked, the tar file would not appear (like in your case).
Hope this helps.

**Comment by PhilLint** [comment]
Thanks for the help. So, to check that out, I once made the backup for only the app and once for both data and app. For the first option, I only get the info and .apk file. When I add data, I get the database file additionally, but still no .tar file. So, does the .db file entail the hitrackfiles somehow? And what do you mean with shared folder? For backup, I can only select SD card, USB or HiSuite.

**Comment by PhilLint** [comment]
When I opened the .db file with SQLite Browser, I found references to hitrack files somewhere hidden. However, I have no clue how to unpack/decrypt/whatever this. Is this a sign, that it is encrypted? Is anyone else getting this db file? I have no clue and after trying every possibility for a backup, I do not get a .tar file. :(

**Comment by CTHRU** [comment]
@PhilLint - Could you verify if the new Huawei Health data export option in version 3.0 works for you (see also #37)? If so, we can close this issue, since the Huawei Backup method became defunct late September 2019.
