### ISSUE TITLE
New type tp=rs

### ISSUE THREAD

**Issue by 413Michele** [aricooperdavis/Huawei-TCX-Converter#21]
There is a new type of data in the files I exported, which is "tp=rs"
I made some testing and it appears to be pace in the format 10*m/s

Here is some sample data:
```
tp=rs;k=0;v=3;
tp=rs;k=5;v=9;
tp=rs;k=10;v=12;
tp=rs;k=15;v=17;
tp=rs;k=20;v=22;
tp=rs;k=25;v=24;
tp=rs;k=30;v=26;
tp=rs;k=35;v=27;
tp=rs;k=40;v=28;
tp=rs;k=45;v=26;
tp=rs;k=50;v=28;
tp=rs;k=55;v=25;
tp=rs;k=60;v=28;
tp=rs;k=65;v=27;
tp=rs;k=70;v=27;
tp=rs;k=75;v=25;
tp=rs;k=80;v=24;
tp=rs;k=85;v=23;
tp=rs;k=90;v=24;
tp=rs;k=95;v=25;
```
Can these be supported too?

**Comment by CTHRU** [comment]
Just to keep you in the loop, the rs (real-time speed) records are currently being used in case of swimming activities. I see potential usage for correct calculation of distances when GPS signal is lost for a longer time during an activity. To be continued.

**Comment by 413Michele** [comment]
Thank you for the update, your tool is really useful!
