### ISSUE TITLE
[BUG] If the track has pauses the conversion doesn't work

### ISSUE THREAD

**Issue by 413Michele** [aricooperdavis/Huawei-TCX-Converter#22]
**Input**
python Huawei-TCX-Converter.py .\HiTrack_1524369828000152438638300030001

**Output**
```
---- Input File ----
reading: FAILED
```

When I remove all the lines like this one, the conversion works as it should:

`tp=lbs;k=752;lat=90.0;lon=-80.0;alt=0.0;t=0.0;`

I got the idea to delete them from here https://github.com/aricooperdavis/Huawei-TCX-Converter/issues/11

If it's needed I can send the Hitrack file privately

**Comment by CTHRU** [comment]
If you want, I invite you to try the version in the forked branch which should solve your issue: https://github.com/CTHRU/Huawei-TCX-Converter
I tried to add handling of pause and stop records in the existing code (had some activities myself with these records that wouldn't work). Note that swimming activities won't work (yet, as is the case in this branch).

**Comment by aricooperdavis** [comment]
I've now merged the @CTHRU commits so this should be supported :-)
