### ISSUE TITLE
[BUG]wrong distance, time and pace of the run. Incorrect gps track display on the map.

### ISSUE THREAD

**Issue by DecabrisT79** [aricooperdavis/Huawei-TCX-Converter#26]
![WrongResult](https://user-images.githubusercontent.com/54700371/63998414-01c9f600-cb3c-11e9-981d-65266786d2f1.jpg)
[HiTrack.zip](https://github.com/aricooperdavis/Huawei-TCX-Converter/files/3558570/HiTrack.zip)

there was no error while executing the program. There are errors in the Result

Thank you for your work. It was supposed to make programmers of Huawei (

**Comment by CTHRU** [comment]
Thank you for reporting the issue and the copy of the files. If you want, you can remove the file from the internet, I will use it only during the debugging. At first sight, the logic for pauze records and/or GPS lost seems to have a defect. Will look into it later.

**Comment by CTHRU** [comment]
I think the bug is squashed in build 1908.3101. If your validation would suggest otherwise, the issue can be reopened.

**Comment by DecabrisT79** [comment]
Yes, problem solved. Now everything is correct.
There is another problem with loading data into Strava, but I'm not sure if this is due to your script.
