### ISSUE TITLE
[BUG] Error convert HiTrack file

### ISSUE THREAD

**Issue by dan1967** [aricooperdavis/Huawei-TCX-Converter#27]
I can not convert my last file. Another previous file is ok.
HiTrack file look same as previous files... for me...

[20190907_163215_R_HiTrack_1567866735000156786849600030001.zip](https://github.com/aricooperdavis/Huawei-TCX-Converter/files/3587480/20190907_163215_R_HiTrack_1567866735000156786849600030001.zip)

Huawei Health app and Watch firmware is without change.

**Comment by CTHRU** [comment]
Probably due to the fact that this activity doesn't have an explicit stop record. Yesterday I was working on support for activities without GPS and I think I squashed this bug by doing so. Just hold on for the next update.

**Comment by CTHRU** [comment]
Should be solved in V2.2. Feel free to re-open if issue persists.

**Comment by dan1967** [comment]
Thank you. Working OK.
