### ISSUE TITLE
[BUG] The --sport command line argument option is not working correctly

### ISSUE THREAD

**Issue by CTHRU** [aricooperdavis/Huawei-TCX-Converter#30]
@dan1967 - I created this separate ticket for your remark in issue #24 concerning the --sport option.

The --sport option was not applied at the time of handling the HiTrack file (did a quick and dirty fix in release 2.2).
There could be a potential conflict with the auto detection of the activity type. Taking the feature for support of open swimming activities #28 into account, I think some rework will be required to the whole auto detection logic together with the implementation of the open water swimming activities as I already noticed that the condition to recognize cycling activities isn't valid anymore because the same condition applies for open water swimming activities (s-r records with value 0).

**Comment by dan1967** [comment]
My opinion - **_--sport_** option is mandatory, not option... ?
