### ISSUE TITLE
Cannot extract backup file

### ISSUE THREAD

**Issue by macieka** [aricooperdavis/Huawei-TCX-Converter#32]
Hi,
this issue is not related to your code, but maybe you saw something like this before.
I have created backup file with HiSuite 9.1.312 for macOS (10.14.5) and saved it on HDD (I don't have sd card right now). When I try to extract it with

`$ tar -zxvf com.huawei.health.tar`

I get following error:

`tar: Unrecognized archive format
tar: Error exit delayed from previous errors.`

`$ file com.huawei.health.tar` returns `com.huawei.health.tar: data`

I'm sure I have unchecked 'Encrypt with password' checkbox. Have you seen this error before? do you think saving backup directly to SD card can bring any difference?

**Comment by aricooperdavis** [comment]
If you backup with the HiSuite application on a Mac/PC the tar files are automatically encrypted, even if you untick the password option. It is more like an option that allows you to specify your own password. Unfortunately the password cannot easily be extracted. Your best bet is to backup locally to your phone's internal storage, or to an SD card.
