### ISSUE TITLE
[BUG] Script won't run without xmlschema library being installed when not using the --validate_xml option

### ISSUE THREAD

**Issue by CTHRU** [aricooperdavis/Huawei-TCX-Converter#36]
Bugreport from @thejoker1971

Hi sir, im having issue running the latest version 2.3... im still using the old version with -v -b arguments... it is working with me but not the newest version 2.3... here are my batch file and error result... and how to use XML validation... i have internet and i already downloaded the XSD file... but still nothing... then how to use PIP INSTALL XMLSCHEMAS... thanks...
________________________________________
batch file
@echo off
echo.
"C:\Users*******\AppData\Local\Programs\Python\Py thon37\python.exe" Huawei-TCX-Converter.py --file %1 --sport Cycle
echo.
pause
________________________________________
error output
Info - External library xmlschema could not be imported.
It is required when using the --validate_xml argument.
It can be installed using: pip install xmlschema
Traceback (most recent call last):
File "Huawei-TCX-Converter.py", line 926, in 
class TcxActivity:
File "Huawei-TCX-Converter.py", line 944, in TcxActivity
filename_prefix: str = None):
NameError: name 'xmlschema' is not defined

**Comment by CTHRU** [comment]
@thejoker1971

A workaround for now is to install the xmlschema library for python. To do this:

1. Open a command prompt in Windows
2. Type 'pip' (without the quotes) on the command prompt, You should see the usage information. If not, it could be that your path variable isn't set. Pip should be in the 'Scripts'subdriectory of your python installation, I think in your case "C:\Users*******\AppData\Local\Programs\Python\Python37\Scripts\pip.exe"
3. Now execute the following command (without the quotes):
'pip install xmlschema'
or
'C:\Users*******\AppData\Local\Programs\Python\Python37\Scripts\pip install xmlschema'

Hope this helps

**Comment by thejoker1971** [comment]
Thank you so much... it is working now... also xmlschema works... hopefully next version there will be "--input_dir" for batch conversion... again thanks...
