### ISSUE TITLE
[NEW FEATURE] Support conversion of Huawei Cloud Motion Path Detail file (see also #19)

### ISSUE THREAD

**Issue by CTHRU** [aricooperdavis/Huawei-TCX-Converter#37]
= #19 (which is closed,  could not find a way to reopen)

**Comment by dan1967** [comment]
My solution... only for me.... I'm not programmer....

This works on Linux.
1. Download data from Huawei Cloud (#19)
2. Decompress file "_/Motion path detail data & description/motion path detail data.json_" and rename to "_motion_data.json_"
3. Convert this file to one record/one line....
`sed -i 's/{"motionPathData":/\n&/g' motion_data.json`

4. Get list of records in format "line date"
`awk -v FS="(\"startTime\":|000\,\"attribute\")" '{print NR, " Time - ", $2=strftime("%Y-%m-%d %H:%M:%S", $2)}' motion_data.json`

5. Extract one "preHiTrack" file for selected record
```
awk -v line="number off line/record" -v FS="(HW_EXT_TRACK_DETAIL\@is|\&\&HW_EXT_TRACK_SIMPLIFY\@is)" 'NR==line {print $2}' motion_data.json > hitrack
```

6. Fix end of line
`sed -i 's/\\n/\n/g' hitrack`

7. "Send" this new hitrack file to TCX-Converter...

This is very bad solution, but works. 
For my purpose I have bash scripts to this with some improvements, but you don't want to see them :-)

1. I have no experience with perl, python, grep, awk.... For programmer is no problem rewrite this to nice solution. 
2. Better solution is work with json in python and get lot of information from backup json file, but this is lot of work...

Finally...
 **TCX converter is VERY NICE tool and THANK YOU VERY MUCH.**

**Comment by CTHRU** [comment]
Thanks for your info, @dan1967 . Seems you're a pro with scripts there! You saved me the time figuring out if the data would be convertible, since you already proved it is.

**Comment by dan1967** [comment]
Hello,
I have little time to play with json and python....
Maybe help this...

[test.txt](https://github.com/aricooperdavis/Huawei-TCX-Converter/files/3683881/test.txt)

**Comment by CTHRU** [comment]
@dan1967 I knew you could program too! We were working in parallel on the same thing in different timezones, lol. Hope you enjoy the new version.
