### ISSUE TITLE
[BUG] [JSON] - more then one activity in one day

### ISSUE THREAD

**Issue by dan1967** [aricooperdavis/Huawei-TCX-Converter#38]
Export only one activity per day.
For example, morning swimming and afternoon running...

from my test python file from last night--- 
```
# list of record
for x in range(len(data)):
    for y in range(len(data[x]["motionPathData"])):
        print(x,"/",y," - ", data[x]["recordDay"], " - ",SportType(data[x]["motionPathData"][y]["sportType"]))

```

Request... Change number of record do start time in export file. From HiTrack_20190831_27 to HiTrack_20190831_100230.

Tomorrow I have nigth work, (same as yesterday). I try fix this...

**Comment by dan1967** [comment]
hello,
I dont know how to commit/pull my version....
I try fix multisport day and add time to filename...

And one more bug...
original
`hitrack_data = re.sub('\&\&HW_EXT_TRACK_SIMPLIFY\@is(.*?)', '', hitrack_data)`

correct
`hitrack_data = re.sub('\&\&HW_EXT_TRACK_SIMPLIFY\@is(.*)', '', hitrack_data)`


[Huawei-TCX-Converter_dan67.zip](https://github.com/aricooperdavis/Huawei-TCX-Converter/files/3692012/Huawei-TCX-Converter_dan67.zip)

**Comment by CTHRU** [comment]
@dan1967 , don't have much time now, but in response to your queston; 'I dont know how to commit/pull my version....'. I saw you already created a fork for your changes, which is good. Normally you should find a button 'Create pull request' on the page of your fork. I'm not sure, but I think only the creator of the repository can merge the pull request (in this case Ari).

**Comment by aricooperdavis** [comment]
That's right, if you modify the code on your fork with your updates then make a pull request then I'll happily merge it :-)
