### ISSUE TITLE
Info - External library xmlschema could not be imported.

### ISSUE THREAD

**Issue by Trepanator56** [aricooperdavis/Huawei-TCX-Converter#45]
When I tried it the first time it worked, but now I am not able to work again, I always get this error message. Actually, I have no idea of Python, so I would appreciate if you can help me solve it.

_Info - External library xmlschema could not be imported.
It is required when using the --validate_xml argument.
It can be installed using: pip install xmlschema_

Thank you,

**Comment by processor286** [comment]
> When I tried it the first time it worked, but now I am not able to work again, I always get this error message. Actually, I have no idea of Python, so I would appreciate if you can help me solve it.
> 
> _Info - External library xmlschema could not be imported. It is required when using the --validate_xml argument. It can be installed using: pip install xmlschema_
> 
> Thank you,

Do you have a pip installation? Did you try 'pip install xmlschema' or 'pip3 install xmlschema' ?

**Comment by CTHRU** [comment]
If you can't get it installed, don't worry. Just remove the --validate_xml argument from the command line. Conversion will still work the same, there is only no online check whether the XML is correctly formatted.

**Comment by processor286** [comment]
For me, the xmlschema was mandatory, it wouldn't run at all without it, regardless of the --validate_xml argument.

**Comment by Trepanator56** [comment]
> Do you have a pip installation? Did you try 'pip install xmlschema' or 'pip3 install xmlschema' ?

Since I have to install pip?  I have tried it from CMD and I think that something I am not doing well.

C:\Users\JYM>python
Python 3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:21:23) [MSC v.1916 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> pip install xmlschema
  File "<stdin>", line 1
    pip install xmlschema
        ^
SyntaxError: invalid syntax
>>> pip3 install xmlschema
  File "<stdin>", line 1
    pip3 install xmlschema
         ^
SyntaxError: invalid syntax
>>>

Thank you,

**Comment by aricooperdavis** [comment]
So you do that on the command line, not in a python interpreter. E.g.

`C:\Users\JYM> pip install xmlschema`
and/or
`C:\Users\JYM> pip3 install xmlschema`

**Comment by Trepanator56** [comment]
Thank you so much everyone.

It's going perfect, it worked with "pip install xmlschema", I swear I'd tried it before and it wasn't going... ;-)

Now perform the conversion without showing any error.

Cheers,
