### ISSUE TITLE
Error line 60

### ISSUE THREAD

**Issue by phoenix-blue** [aricooperdavis/Huawei-TCX-Converter#46]
Hi,

I use at this moment (because i have no Root Phone) the JSON option from the online backup way.
when i put the "motion path detail data.json" file inside the same folder as the Huawei-TCX-Converter.py script and use the following command;

`python Huawei-TCX-Converter.py --json "motion path detail data.json" --from_date 2020-01-01 --output_dir /json `

I get the next error:

```
  File "Huawei-TCX-Converter.py", line 60
    def __init__(self, activity_id: str, activity_type: str = TYPE_UNKNOWN):
                                  ^
SyntaxError: invalid syntax
```

I have also try the next Arguments -> --sport Run
But with the same error, is there something i do wrong?

**Comment by CTHRU** [comment]
I just got the sources and ran your command. Very strange you get a syntax error, indicating that the program code is not a valid Python statement.

Could you verify your Python version (3.7.3 or above) and/or try to get the source file again from GitHub? If the problem persists, don't hesitate to let us know.

**Comment by phoenix-blue** [comment]
Hi,

After some try and error i have found that Python was in the first place the problem, I have installed on my raspi  "python" version 2.7 and "python3"version 3.7.3.

So with an little change to:

`python3 Huawei-TCX-Converter.py --json "motion path detail data.json" --from_date 2020-01-01 --output_dir /output/json`

I have some other feedback but not the result i'm looking for, but because i have found this part in the text `PermissionError: [Errno 13] Permission denied: '/output/json/HiTrack_20200105_163120_13.tcx'` I have insert sudo to the command.

`sudo python3 Huawei-TCX-Converter.py --json "motion path detail data.json" --from_date 2020-01-01 --output_dir /output/json`

And....it's working..nice.
Thanks for the push in the right direction!

**Comment by CTHRU** [comment]
Thank you for your feedback. Will close this issue.
