### ISSUE TITLE
help here please

### ISSUE THREAD

**Issue by 1kaiser** [aricooperdavis/Huawei-TCX-Converter#47]
https://github.com/Freeyourgadget/Gadgetbridge/issues/1021 
@aricooperdavis @ckudera on the usage of 

> ImportError: /home/schlboy26/libwhiteBoxJniLib.so: cannot open shared object file: No such file or directory

![scrnli_1_18_2020_8-49-58 AM](https://user-images.githubusercontent.com/26379748/72657866-ec147a80-39cf-11ea-8a48-1e762257c8b4.png)

**Comment by CTHRU** [comment]
Did you post your question in the correct project? Your question seems not related to the Huawei-TCX-Converter project.

**Comment by 1kaiser** [comment]
No it's not but it is possible @ckudera proposed how to extract from database using some methods, it would be helpful if the database can be extracted like tcx converter project. I wasn't able to post the issue to gadget bridge as they have moved to another site.

**Comment by aricooperdavis** [comment]
You can still [file issues for GadgetBridge](https://codeberg.org/Freeyourgadget/Gadgetbridge/issues/new). Closing as your issue isn't relevant to this project.
