### ISSUE TITLE
[BUG] /usr/bin/python: can't find '__main__' module in 'Huawei-TCX-Converter'

### ISSUE THREAD

**Issue by deperchin** [aricooperdavis/Huawei-TCX-Converter#48]
Hi, i hava this issue : 

/usr/bin/python: can't find '__main__' module in 'Huawei-TCX-Converter'

When i try to convert json to tcx file, anything have a solution for this ?

**Comment by CTHRU** [comment]
This could be a python version problem. Could you check which version you're using by just typing python on the command prompt? You need at least version 3.7.3.

**Comment by deperchin** [comment]
I check, this is 3.8.1 version, the latest version

**Comment by CTHRU** [comment]
We need to look further. I just tested the script myself (on linux) using python version 3.8.1 to make sure and it runs just fine on my system.
1. I think a possibility could be in your case that there are multiple python versions installed next to each other. The default python version on linux would be 2.7 or so (executable is indeed /usr/bin/python). The 3.8.1 version installed as usr/bin/python**3** executable in my case. so if I run 'python Huawei-TCX-converter.py --help' it fails whereas running 'python**3** Huawei-TCX-converter.py --help' it works.
2. Second possibility is maybe the source file itself, that in some way isn't completely downloaded or got mixed up in some way. You could try to download the Huawei-TCX-converter.py again and see if it makes any difference.

**Comment by deperchin** [comment]
i retry and it works but i didn't fin my directory : /my_output_dir/json with the hitrack files, where is this ?

**Comment by CTHRU** [comment]
I see we will need to adapt our examples in the readme file a bit.
Unfortunately the example contains a / at the beginning which saves the output in the requested directory on the root of your drive. If you type 'cd /' and then 'ls' you should find your folder.
To generate in a subfolder from the folder where the python script is, just remove the / at the beginning of the --output_dir option.

**Comment by CTHRU** [comment]
Fyi, I just updated the readme file to reflect the changes explained in my answer above.

**Comment by deperchin** [comment]
Thanks for your answer, i change the route and it works !

**Comment by CTHRU** [comment]
You're welcome. Enjoy using the converter. Will close this issue.
