### ISSUE TITLE
Only 4 Hitrack files show up

### ISSUE THREAD

**Issue by song85129** [aricooperdavis/Huawei-TCX-Converter#9]
Hi, this is a great project.
However, I was using backup to the network drive option and after unzip the tar file. I can only find 4 Hitrack files dated back to January.
I opened each record on the phone however, it didn't seem to generate new Hitrack files.

I wonder if anyone has similar problem.

**Comment by aricooperdavis** [comment]
I hope this isn't a change by Huawei to close down this workaround! I'll have an explore this evening and see if I can replicate it :)

**Comment by aricooperdavis** [comment]
I can't seem to replicate the problem of not generating new HiTrack files I'm afraid, and I can't think of what might be causing it. It seems likely that the files are deleted at some point, so perhaps there is a maximum number that the app generates at once? Maybe try viewing and backing up in small batches to ensure that the HiTrack files aren't removed?

**Comment by Fultonius** [comment]
Hi, I have a rooted android phone and I am trying to find the HiTrack files from by Band 3 Pro. I cannot seem to find any HiTrack files, or anything names .tar. I'm wondering if Huawei have gotten wise to the hack and have found a better way of hiding the data?

**Comment by tzeseng** [comment]
Hi
After run the command, all the HiTrack file i try is generating **distance with "0 m"**, as below:
---- Input File ----
reading: OKAY
filtering: OKAY
processing gps: OKAY
processing heart-rate/cadence: OKAY
---- Details ----
sport: Running
start: 2019-07-16 12:10:40
duration: 00:00:56
**distance: 0m**

**Comment by aricooperdavis** [comment]
@tzeseng I've opened [a new issue](https://github.com/aricooperdavis/Huawei-TCX-Converter/issues/18) for this, as it's not relevant to this issue. Please follow up with details there.
